# This is a basic workflow to help you get started with Actions

name: Testing gource

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
    push:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        name: Setting up gource

        steps:
            - uses: actions/checkout@v2
            - name: Install gource & xvfb
              run: sudo apt-get install gource xvfb -y
            - name: Install ffmpeg & gifski
              run: sudo apt-get update && sudo snap install ffmpeg gifski
            - name: Run gource with xvfb
              run: xvfb-run --auto-servernum --server-num=99 gource -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
            - name: create frames dir
              run: mkdir frames
            - name: Create images from video & del video
              run: ffmpeg -i ./gource.mp4  -r 5 frames/%04d.png && rm ./gource.mp4
            - name: del old gif & Create gif from images & del frames
              run: rm -f ./gource.gif && gifski -o gource.gif ./frames/*.png && rm -rf ./frames
            - name: List directory contents
              run: sudo find .
            - name: Setup git
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: 'main' #optional defaults to master